#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026 Rigby Foundation
"""Turn `llvm-nm -n` output of a linked kernel into a C symbol table
(kernel/lib/symtab.c uses it to name addresses in crash dumps)."""
import sys

syms = []
for line in sys.stdin:
    parts = line.split()
    if len(parts) != 3 or parts[1] not in "TtWw":
        continue
    addr, name = int(parts[0], 16), parts[2]
    if name.startswith("__ksym_") or name.startswith(".L"):
        continue
    syms.append((addr, name))
syms.sort()
print("/* generated by scripts/gensyms.py: do not edit */")
print("#include \"types.h\"")
print("const struct kernel_sym { uint64_t addr; const char *name; } kernel_syms[] = {")
for addr, name in syms:
    print("    { 0x%x, \"%s\" }," % (addr, name))
print("    { 0, 0 },")
print("};")
print("const unsigned kernel_sym_count = %d;" % len(syms))
